// CalComProvider — CalendarProvider backed by Cal.com's v1 REST API. Uses a
// personal API key (generated by the user in Cal.com → Settings → Developer →
// API Keys). No OAuth refresh needed; keys don't expire unless revoked.

import type {
  CalendarProvider,
  EventType,
  Booking,
  Attendee,
  ListBookingsInput,
} from "./provider";

const API = "https://api.cal.com/v1";

export type CalComCredentials = {
  api_key?: string | null;
  username?: string | null;
};

export type CalComProviderOptions = {
  credentials: CalComCredentials;
};

type RawAttendee = {
  name?: string;
  email?: string;
  timeZone?: string;
};

type RawBooking = {
  id: number | string;
  uid?: string;
  title?: string;
  eventTypeId?: number | string | null;
  eventType?: { title?: string };
  startTime?: string;
  endTime?: string;
  status?: string;
  attendees?: RawAttendee[];
  location?: string | null;
  description?: string | null;
};

type RawEventType = {
  id: number | string;
  title?: string;
  slug?: string;
  length?: number;
  description?: string | null;
  hidden?: boolean;
};

export class CalComProvider implements CalendarProvider {
  readonly providerName = "calcom";
  private readonly apiKey: string;
  private readonly username: string | null;

  constructor(opts: CalComProviderOptions) {
    const key = opts.credentials.api_key;
    if (!key) throw new Error("CalComProvider: no api_key in credentials");
    this.apiKey = key;
    this.username = opts.credentials.username ?? null;
  }

  async listEventTypes(limit = 20): Promise<EventType[]> {
    const res = await this.fetch<{ event_types: RawEventType[] }>(
      `/event-types`,
    );
    const rows = (res.event_types ?? []).slice(0, Math.max(1, Math.min(100, limit)));
    return rows.map((r): EventType => {
      const slug = r.slug ?? "";
      const url = this.username ? `https://cal.com/${this.username}/${slug}` : "";
      return {
        id: String(r.id),
        title: r.title ?? "(untitled)",
        slug,
        length_minutes: r.length ?? 30,
        description: r.description ?? "",
        url,
        hidden: Boolean(r.hidden),
      };
    });
  }

  async listBookings(input: ListBookingsInput): Promise<Booking[]> {
    const params = new URLSearchParams();
    if (input.status) params.set("status", input.status);
    const res = await this.fetch<{ bookings: RawBooking[] }>(
      `/bookings${params.toString() ? `?${params.toString()}` : ""}`,
    );
    const rows = (res.bookings ?? []).slice(0, Math.max(1, Math.min(200, input.limit ?? 50)));
    return rows.map((r) => mapBooking(r));
  }

  async getBooking(id: string): Promise<Booking> {
    const res = await this.fetch<{ booking: RawBooking }>(`/bookings/${id}`);
    return mapBooking(res.booking);
  }

  async cancelBooking(id: string, reason?: string): Promise<void> {
    const body = reason ? { cancellationReason: reason } : {};
    await this.fetch(`/bookings/${id}/cancel`, {
      method: "DELETE",
      body: JSON.stringify(body),
    });
  }

  async getSchedulingUrl(): Promise<string> {
    if (this.username) return `https://cal.com/${this.username}`;
    // Fall back to looking up the /me endpoint.
    const res = await this.fetch<{ user?: { username?: string } }>(`/me`);
    const username = res.user?.username;
    if (username) return `https://cal.com/${username}`;
    return "https://cal.com";
  }

  private async fetch<T>(path: string, init?: RequestInit): Promise<T> {
    // Cal.com v1 auth: ?apiKey=... query param (NOT an Authorization header).
    const joiner = path.includes("?") ? "&" : "?";
    const url = `${API}${path}${joiner}apiKey=${encodeURIComponent(this.apiKey)}`;
    const res = await fetch(url, {
      ...init,
      headers: {
        "Content-Type": "application/json",
        ...((init?.headers as Record<string, string>) ?? {}),
      },
    });
    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Cal.com ${init?.method ?? "GET"} ${path} ${res.status}: ${text}`);
    }
    return (await res.json()) as T;
  }
}

function mapBooking(r: RawBooking): Booking {
  const attendees: Attendee[] = (r.attendees ?? []).map((a) => ({
    name: a.name ?? "",
    email: a.email ?? "",
    timezone: a.timeZone ?? null,
  }));
  const status = (r.status ?? "accepted").toLowerCase() as Booking["status"];
  const url = r.uid ? `https://cal.com/booking/${r.uid}` : "";
  return {
    id: String(r.id),
    title: r.title ?? r.eventType?.title ?? "(untitled)",
    event_type: r.eventType?.title ?? null,
    start: r.startTime ?? "",
    end: r.endTime ?? "",
    status,
    attendees,
    location: r.location ?? null,
    description: r.description ?? "",
    url,
  };
}
